##Plugin configuration
tag: '&r[&cCreativeManager&r] '
lang: en_EN
log: true
## Protection module
container-protection: true #Bypass : creativemanager.container
spawn-protection: true #Bypass : creativemanager.spawner
drop-protection: true #Bypass : creativemanager.drop
pickup-protection: true #Bypass : creativemanager.pickup
build-protection: true #Bypass : creativemanager.build
entity-protection: true #Bypass : creativemanager.entity
pvp-protection: true #Bypass : creativemanager.hit.player
hitmonster-protection: true #Bypass : creativemanager.hit.monster
## Multi inventory
adventure-inventory: true
creative-inventory: true #Bypass : cm.bypass.inventory
## Black List
blacklist:
  place: #Bypass : creativemanager.bypass.blacklist.place
    - 'tnt'
  use: #Bypass : creativemanager.bypass.blacklist.use
    - 'lava_bucket'
    - 'flint_and_steel'
    - 'fire_charge'
  get: #Bypass : creativemanager.bypass.blacklist.get
    - 'diamond'
## Lore settings
add-lore: true
creative-lore:
  - '&5Creative {ITEM}'
  - '&7Generate by {PLAYER}'
  - '&7{UUID}'